FROM registry.access.redhat.com/ubi8/php-74@sha256:267ee7fa444c157d3bab68b8fa01d2862ec15a6d487e4b0836b9b8ea2be1e414

# Add application sources to a directory that the assemble script expects them
# and set permissions so that the container runs without root access
USER 0
ADD app-src /tmp/src
RUN chown -R 1001:0 /tmp/src
USER 1001

# Install the dependencies
RUN /usr/libexec/s2i/assemble

# Set the default command for the resulting image
CMD /usr/libexec/s2i/run
